### ISSUE TITLE
testdataについて

### ISSUE THREAD

**Issue by takanobu-watanabe** [ku-nlp/bert-based-faqir#1]
テストデータの入力についての仕様が以下のようになっています。
```
A, Contain correct information.
B, Contain relevant information.
C, The topic is same as a query, but does not contain relevant information.
```

以下の場合、それぞれどれがA、B、Cになるのでしょうか？
＜例＞
尼崎城は常時イベントなどは行う予定でしょうか	1723 1420	1620 915 1685 1563 1504 1366	None

**Comment by sktwtrg** [comment]
タブ区切りになっていて質問文の次のブロックから順にA, B, Cのidのリストを表しています。idのリストはスペース区切りになっています。
例の場合だと1723, 1420がカテゴリAに属するQAのID、1620, 915, 1685. 1563, 1504, 1366がカテゴリBに属するQAのIDとなり、またカテゴリCのものはないことを表しています。

**Comment by takanobu-watanabe** [comment]
ご回答ありがとうございました。理解できました。
